name: Deploy backend on vps

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
