name: Deploy front of Hippochat on VPS

on:
  push:
    branches:
      - "main"
    paths:
      - "front/**"
  workflow_dispatch:

env:
  REIGSTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}-front

jobs:
  ionic:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ionic
        uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn add ionic
      - run: ionic build

  build-and-push-image:
    runs-on: ubuntu-latest

    needs: ionic

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.REIGSTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.REIGSTRY}}/${{env.IMAGE_NAME}}

      - name: Build and push the docker image
        uses: docker/build-push-action@v4
        with:
          context: ./front/
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - uses: actions/checkout@v3
    
      - name: Deploy compose on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.VPS}}
          username: ${{secrets.VPS_USERNAME}}
          key: ${{secrets.VPS_PRIVATE_KEY}}
          script: |
            docker compose -f /home/hippochat/docker-compose.yml down
            docker system prune -f
            docker compose -f /home/hippochat/docker-compose.yml pull
            docker compose -f /home/hippochat/docker-compose.yml up -d
